FROM python:3.8-buster

RUN apt-get update; apt-get install -y pv build-essential

ENV FLASK_APP="knowledge:app"
ENV DATA_DIRECTORY="/knowledge/data"
ENV CONFIG_DIRECTORY="/knowledge/config"

EXPOSE 5000
VOLUME ${DATA_DIRECTORY}

WORKDIR /knowledge

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "flask", "run", "--host", "0.0.0.0" ]
