FROM python:3.8-alpine

RUN apk add --update pv make

EXPOSE 5000
VOLUME [ "/knowledge/data" ]

ENV DATA_DIR "/knowledge/data"
ENV FLASK_APP "knowledge:app"

WORKDIR /knowledge

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "flask", "run", "--host", "0.0.0.0" ]
